### ISSUE TITLE
deploy_all failing

### ISSUE THREAD

**Issue by clazzaro** [hassenius/MicroservicesShop#3]
Does the deploy script need updates?  Can this be done with a deploy to bluemix button?

the ./deploy_all.sh script fails:
Creating service instance myMicroservicesCloudant in org clazzaro@us.ibm.com / space dev as clazzaro@us.ibm.com...
FAILED
Could not find plan with name Shared
Creating service instance myServiceDiscovery in org clazzaro@us.ibm.com / space dev as clazzaro@us.ibm.com...
FAILED
Service offering service_discovery not found

**Comment by hassenius** [comment]
Service Discovery retired. Fixed with last commits
